#!/usr/bin/env python3
"""
design_doc.py — Design Doc Gate for doc-index (v1)

Makes a project *design doc* a first-class doc-index citizen. Shared by
serve.py (first-deploy preflight) and scan.py (freshness + the pinned PWA card).

Behaviour is driven entirely by the `design_doc:` block in doc-index.yaml:

    design_doc:
      enabled: true            # off -> this whole feature is a no-op
      path: docs/DESIGN.md      # canonical location (relative to repo)
      required_on_init: true    # init ensures one exists; fails loud if it truly can't
      template: default         # default | minimal | <path to a custom .md>
      proposal_ledger: true     # keep a Proposal Ledger section
      auto_snapshot:
        enabled: false
        generator: ""           # project-specific snapshot generator (optional)
        max_age_h: 25

Design principles carried over from the health-digest work:
  - Absence is a signal. A missing / unfilled / stale design doc is reported,
    never silently green.
  - Non-destructive. We never overwrite a human-authored doc; we only create a
    seed when none exists, or append missing scaffolding to an existing one.
  - Fail loud, but don't block. On first deploy we always try to leave a doc in
    place (D1: auto-seed, non-blocking); we return an error only on a real IO
    failure, and the caller surfaces it.

Standard library only. Python 3.8+.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

GREEN = "\U0001F7E2"   # 🟢
YELLOW = "\U0001F7E1"  # 🟡
RED = "\U0001F534"     # 🔴

AUTO_START = "<!-- AUTO:START"
AUTO_END = "<!-- AUTO:END -->"
UNFILLED_MARKER = "_(To fill in"           # present in the seed's placeholder lines
LEDGER_HEADING = "## Proposal Ledger"
_TS_RE = re.compile(r"last-generated:\s*(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})")

# Heuristics for "the project already has design content, just not at the
# canonical path" (branch B). Case-insensitive basename globs.
_SCATTERED_GLOBS = ("DESIGN.md", "ARCHITECTURE.md", "*design*.md", "*DESIGN*.md")
_SCATTERED_DIRS = ("docs/20-design",)
_DEFAULT_IGNORE = {".git", "node_modules", "__pycache__", ".venv", ".cache"}


# ── config ────────────────────────────────────────────────────────────────────

def dd_config(cfg):
    """Return the normalized design_doc config (with defaults applied)."""
    dd = dict(cfg.get("design_doc") or {})
    dd.setdefault("enabled", True)
    dd.setdefault("path", "docs/DESIGN.md")
    dd.setdefault("required_on_init", True)
    dd.setdefault("template", "default")
    dd.setdefault("proposal_ledger", True)
    snap = dict(dd.get("auto_snapshot") or {})
    snap.setdefault("enabled", False)
    snap.setdefault("generator", "")
    snap.setdefault("max_age_h", 25)
    dd["auto_snapshot"] = snap
    return dd


def _ignore_names(cfg):
    names = set(_DEFAULT_IGNORE)
    for pat in (cfg.get("repo", {}) or {}).get("ignore", []):
        # only treat plain directory names as prune targets; globs stay for files
        if not any(ch in pat for ch in "*?[]"):
            names.add(pat)
    return names


# ── detection ───────────────────────────────────────────────────────────────

def find_existing(repo_path, canonical_rel, ignore_names):
    """Classify what design content the repo already has.

    Returns (state, paths): state is "canonical" | "scattered" | "none".
    """
    repo = Path(repo_path)
    canonical = (repo / canonical_rel).resolve()
    if canonical.is_file():
        return "canonical", [canonical]

    from fnmatch import fnmatch
    hits = []
    for dirpath, dirnames, filenames in os.walk(repo):
        dirnames[:] = [d for d in dirnames if d not in ignore_names]
        for fn in filenames:
            full = Path(dirpath) / fn
            if full.resolve() == canonical:
                continue
            if any(fnmatch(fn.lower(), g.lower()) for g in _SCATTERED_GLOBS):
                hits.append(full)
    # explicit design dirs
    for d in _SCATTERED_DIRS:
        dd = repo / d
        if dd.is_dir():
            for full in sorted(dd.rglob("*.md")):
                if full.resolve() != canonical and full not in hits:
                    hits.append(full)
    hits = sorted(set(hits))
    return ("scattered", hits) if hits else ("none", [])


# ── template rendering ────────────────────────────────────────────────────────

def _templates_dir():
    return Path(__file__).resolve().parent.parent / "templates"


_MINIMAL_SEED = """# {{PROJECT_NAME}} · Design Doc

> Single source of intent. Generated by doc-index on {{DATE}}.
> Governance: Proposal -> Approved -> Landed here -> Implemented.

## What this project is

_(To fill in.)_

## Proposal Ledger

| # | Date | Title | Status | Approved by | Landed | Detail |
|---|------|-------|--------|-------------|--------|--------|
| — | — | _(no proposals yet)_ | — | — | — | — |
"""


def render_seed(template_choice, project_name, now=None):
    """Return the seed markdown for a new DESIGN.md."""
    now = now or datetime.now(timezone.utc)
    date = now.strftime("%Y-%m-%d")
    if template_choice == "minimal":
        text = _MINIMAL_SEED
    elif template_choice in ("default", "", None):
        tpl = _templates_dir() / "DESIGN.template.md"
        text = tpl.read_text(encoding="utf-8")
    else:  # custom path
        text = Path(template_choice).expanduser().read_text(encoding="utf-8")
    return text.replace("{{PROJECT_NAME}}", project_name).replace("{{DATE}}", date)


def _project_name(cfg):
    return (cfg.get("project", {}) or {}).get("name", "This Project")


# ── the init preflight ────────────────────────────────────────────────────────

def ensure(cfg, repo_path):
    """First-deploy preflight. Returns (ok, action, msg).

    action is one of: disabled | adopt | incorporate | generate | error.
    """
    dd = dd_config(cfg)
    if not dd["enabled"]:
        return True, "disabled", "design_doc.enabled is false — skipped"

    canonical_rel = dd["path"]
    canonical = Path(repo_path) / canonical_rel
    state, found = find_existing(repo_path, canonical_rel, _ignore_names(cfg))

    try:
        if state == "canonical":
            added = _backfill_scaffolding(canonical, dd)
            if added:
                return True, "adopt", f"adopted existing {canonical_rel}; added missing: {', '.join(added)}"
            return True, "adopt", f"adopted existing {canonical_rel} (already complete)"

        seed = render_seed(dd["template"], _project_name(cfg))

        if state == "scattered":
            seed = _append_incorporate_section(seed, canonical, found)
            _write(canonical, seed)
            rels = ", ".join(str(p.relative_to(repo_path)) for p in found)
            return True, "incorporate", (
                f"generated canonical {canonical_rel} indexing {len(found)} existing "
                f"design doc(s) in place [{rels}]"
            )

        _write(canonical, seed)
        return True, "generate", f"generated seed {canonical_rel} (fill in its intent sections)"

    except OSError as e:
        # required_on_init: a real IO failure is loud, not silent.
        return False, "error", f"could not ensure {canonical_rel}: {e}"


def _write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _backfill_scaffolding(canonical: Path, dd) -> list:
    """Append only the structural pieces an adopted doc is missing. Never edits
    existing prose. Returns the list of things added."""
    text = canonical.read_text(encoding="utf-8", errors="ignore")
    added, appendix = [], []
    if dd["proposal_ledger"] and LEDGER_HEADING not in text:
        appendix.append(
            "\n\n" + LEDGER_HEADING + "\n\n"
            "Every change lands here before it is built.\n\n"
            "| # | Date | Title | Status | Approved by | Landed | Detail |\n"
            "|---|------|-------|--------|-------------|--------|--------|\n"
            "| — | — | _(no proposals yet)_ | — | — | — | — |\n"
        )
        added.append("Proposal Ledger")
    if dd["auto_snapshot"]["enabled"] and AUTO_START not in text:
        appendix.append(
            "\n\n## Live config snapshot\n\n" + AUTO_START + " -->\n" + AUTO_END + "\n"
        )
        added.append("AUTO snapshot markers")
    if appendix:
        if not text.endswith("\n"):
            text += "\n"
        canonical.write_text(text + "".join(appendix), encoding="utf-8")
    return added


def _append_incorporate_section(seed: str, canonical: Path, found) -> str:
    """Append a section that links (does not move) existing design docs."""
    lines = ["\n\n## Existing design docs (indexed)\n",
             "_These were already in the repo; linked here in place — originals untouched._\n"]
    base = canonical.parent
    for p in found:
        try:
            rel = os.path.relpath(p, base)
        except ValueError:
            rel = str(p)
        lines.append(f"- [{p.name}]({rel})")
    return seed + "\n".join(lines) + "\n"


# ── freshness (absence is a signal) ───────────────────────────────────────────

def freshness(cfg, repo_path, now=None):
    """Return (flag, detail, reasons) for the design doc. Emoji flags match the
    health-digest module so a digest can reuse this verbatim."""
    now = now or datetime.now(timezone.utc)
    dd = dd_config(cfg)
    if not dd["enabled"]:
        return GREEN, "design doc disabled", []
    canonical = Path(repo_path) / dd["path"]
    if not canonical.is_file():
        return RED, f"{dd['path']} missing", [f"design doc not found at {dd['path']}"]
    text = canonical.read_text(encoding="utf-8", errors="ignore")
    reasons = []

    if UNFILLED_MARKER in text:
        reasons.append("seed not filled in yet (intent sections are placeholders)")

    snap = dd["auto_snapshot"]
    if snap["enabled"]:
        m = _TS_RE.search(text)
        if not m:
            reasons.append("auto_snapshot enabled but no last-generated timestamp (generator hasn't run?)")
        else:
            try:
                gen = datetime.strptime(m.group(1), "%Y-%m-%dT%H:%M").replace(tzinfo=timezone.utc)
                age_h = (now - gen).total_seconds() / 3600.0
                if age_h > snap["max_age_h"]:
                    reasons.append(f"snapshot {int(age_h)}h old > {snap['max_age_h']}h limit")
            except ValueError:
                reasons.append("snapshot timestamp unparseable")

    if any("missing" in r or "limit" in r or "hasn't run" in r or "unparseable" in r for r in reasons):
        flag = RED
    elif reasons:
        flag = YELLOW   # unfilled seed
    else:
        flag = GREEN
    return flag, ("ok" if not reasons else "; ".join(reasons)), reasons


def ledger_counts(text):
    """Count proposal rows by status from the Proposal Ledger table."""
    counts = {}
    in_ledger = False
    for line in text.splitlines():
        if line.strip().startswith(LEDGER_HEADING):
            in_ledger = True
            continue
        if in_ledger:
            if line.startswith("## ") and LEDGER_HEADING not in line:
                break
            if line.lstrip().startswith("|"):
                cells = [c.strip() for c in line.strip().strip("|").split("|")]
                if len(cells) >= 4:
                    # Only real rows match a known status; the header ("Status"),
                    # separator ("---") and placeholder ("—") rows match nothing.
                    status = cells[3].lower()
                    if status in ("proposed", "approved", "landed", "implemented", "superseded"):
                        counts[status] = counts.get(status, 0) + 1
    return counts


# ── PWA card ──────────────────────────────────────────────────────────────────

def _esc(t):
    return (str(t).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def card_html(cfg, repo_path, url_base=None):
    """Render the pinned design-doc card for the top of the PWA. Empty string
    when the feature is disabled."""
    dd = dd_config(cfg)
    if not dd["enabled"]:
        return ""

    flag, detail, reasons = freshness(cfg, repo_path)
    canonical = Path(repo_path) / dd["path"]
    href = "docs/" + quote(dd["path"], safe="/")

    if not canonical.is_file():
        badge_cls, badge = "dd-red", "missing"
        meta = "no design doc — run serve.py init or design-doc adopt"
        return _render_card(href, badge_cls, badge, meta, clickable=False)

    text = canonical.read_text(encoding="utf-8", errors="ignore")
    if flag == RED:
        badge_cls, badge = "dd-red", "stale"
    elif flag == YELLOW:
        badge_cls, badge = "dd-amber", "unfilled"
    else:
        badge_cls, badge = "dd-green", "fresh"

    counts = ledger_counts(text) if dd["proposal_ledger"] else {}
    open_bits = []
    if counts.get("proposed"):
        open_bits.append(f"{counts['proposed']} proposed")
    if counts.get("approved"):
        open_bits.append(f"{counts['approved']} approved awaiting land")
    if open_bits:
        meta = " · ".join(open_bits)
    elif badge == "unfilled":
        meta = "needs its intent sections filled in"
    else:
        meta = "no open proposals"
    return _render_card(href, badge_cls, badge, meta, clickable=True)


def _render_card(href, badge_cls, badge, meta, clickable):
    tag_open = f'<a class="dd-main file-item" href="{_esc(href)}">' if clickable else '<div class="dd-main">'
    tag_close = "</a>" if clickable else "</div>"
    return (
        '<div class="design-card">\n'
        f'    {tag_open}\n'
        '        <span class="dd-icon">📐</span>\n'
        '        <span class="dd-info">\n'
        '            <span class="dd-title">Design Doc</span>\n'
        f'            <span class="dd-meta">{_esc(meta)}</span>\n'
        '        </span>\n'
        f'        <span class="dd-badge {badge_cls}">{_esc(badge)}</span>\n'
        f'    {tag_close}\n'
        '</div>'
    )
