#!/usr/bin/env python3
"""
Doc Index Deployment — Initialize and configure deployment for a doc index site.

Usage:
  python3 serve.py init <config.yaml>     # Full setup
  python3 serve.py status <config.yaml>   # Check deployment status
  python3 serve.py nginx <config.yaml>    # Print nginx config snippet
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

import yaml


def load_config(path):
    with open(path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    cfg["repo"]["path"] = str(Path(cfg["repo"]["path"]).expanduser())
    cfg["serve"]["root"] = str(Path(cfg["serve"]["root"]).expanduser())
    return cfg


def check_nginx():
    """Check if nginx is installed and running."""
    # Check installed
    result = subprocess.run(["which", "nginx"], capture_output=True, text=True)
    if result.returncode != 0:
        return False, "nginx not found in PATH"

    # Check running
    result = subprocess.run(["systemctl", "is-active", "nginx"], capture_output=True, text=True)
    if result.stdout.strip() != "active":
        return False, "nginx is not running (systemctl is-active: " + result.stdout.strip() + ")"

    return True, "nginx is running"


def check_repo(path):
    """Check if repo path exists and is a git repo."""
    p = Path(path)
    if not p.is_dir():
        return False, f"Repo path not found: {path}"
    if not (p / ".git").is_dir():
        return False, f"Not a git repository: {path} (no .git directory)"
    return True, f"Repo found: {path}"


def create_serve_dir(serve_root):
    """Create the serve directory."""
    p = Path(serve_root)
    if p.exists():
        return True, f"Serve directory already exists: {serve_root}"
    p.mkdir(parents=True, exist_ok=True)
    return True, f"Created serve directory: {serve_root}"


def create_docs_symlink(serve_root, repo_path):
    """Create docs -> repo symlink."""
    docs_link = Path(serve_root) / "docs"
    if docs_link.is_symlink():
        target = os.readlink(docs_link)
        if target == repo_path:
            return True, f"Symlink already correct: docs -> {repo_path}"
        else:
            return False, f"Symlink exists but points to {target}, expected {repo_path}"
    elif docs_link.exists():
        return False, f"docs/ exists but is not a symlink — remove it manually"

    os.symlink(repo_path, docs_link)
    return True, f"Created symlink: docs -> {repo_path}"


def generate_icons(serve_root, cfg):
    """Generate PWA icons if they don't exist."""
    icon_192 = Path(serve_root) / "icon-192.png"
    icon_512 = Path(serve_root) / "icon-512.png"

    if icon_192.exists() and icon_512.exists():
        return True, "Icons already exist"

    # Try using icon.py
    icon_script = Path(__file__).parent / "icon.py"
    if icon_script.exists():
        short_name = cfg["project"].get("short_name", "Doc")
        color = cfg["project"].get("color", "#2d5f8a")
        subprocess.run(
            [sys.executable, str(icon_script), short_name, color, serve_root],
            capture_output=True, text=True
        )
        if icon_192.exists():
            return True, "Icons generated by icon.py"

    return False, "Could not generate icons — run icon.py manually or place icon-192.png and icon-512.png"


def copy_templates(serve_root):
    """Copy viewer templates to serve directory."""
    template_dir = Path(__file__).parent.parent / "templates"
    copied = []
    for fname in ["sw.js", "viewer.html", "md-viewer.html"]:
        src = template_dir / fname
        dst = Path(serve_root) / fname
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)
            copied.append(fname)
    if copied:
        return True, f"Copied templates: {', '.join(copied)}"
    return True, "Templates already in place"


def validate_cron_expr(expr):
    """Validate cron expression has 5 fields with safe characters only."""
    import re
    fields = expr.strip().split()
    if len(fields) != 5:
        return False, f"Cron expression must have 5 fields, got {len(fields)}"
    # Each field: digits, *, /, -, comma only
    pattern = re.compile(r'^[0-9*/,-]+$')
    for i, field in enumerate(fields):
        if not pattern.match(field):
            return False, f"Cron field {i+1} contains invalid characters: {field!r}"
    return True, "valid"


def setup_cron(cfg, config_path):
    """Set up cron job if configured."""
    cron_expr = cfg.get("triggers", {}).get("cron", "")
    if not cron_expr:
        return True, "No cron configured (triggers.cron is empty)"

    # Validate cron expression to prevent command injection
    valid, msg = validate_cron_expr(cron_expr)
    if not valid:
        return False, f"Invalid cron expression: {msg}"

    scan_script = Path(__file__).parent / "scan.py"
    config_abs = str(Path(config_path).resolve())
    cron_cmd = f"{cron_expr} {sys.executable} {scan_script} {config_abs} >> {cfg['serve']['root']}/scan.log 2>&1"

    # Check existing crontab
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    existing = result.stdout if result.returncode == 0 else ""

    # Check if already set
    if config_abs in existing:
        return True, "Cron job already exists"

    # Add new cron entry
    new_crontab = existing.rstrip() + "\n" + cron_cmd + "\n"
    proc = subprocess.run(["crontab", "-"], input=new_crontab, capture_output=True, text=True)
    if proc.returncode == 0:
        return True, f"Cron job added: {cron_cmd}"
    else:
        return False, f"Failed to set cron: {proc.stderr}"


def run_initial_scan(cfg, config_path):
    """Run scan.py to generate initial index."""
    scan_script = Path(__file__).parent / "scan.py"
    config_abs = str(Path(config_path).resolve())
    result = subprocess.run(
        [sys.executable, str(scan_script), config_abs],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        return True, "Initial scan completed:\n" + result.stdout
    else:
        return False, "Scan failed:\n" + result.stderr + "\n" + result.stdout


def _make_htpasswd_line(user, password):
    """Build a `user:hash` line. Tries htpasswd (bcrypt), then openssl APR1."""
    try:
        out = subprocess.run(
            ["htpasswd", "-nbB", user, password],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass
    try:
        out = subprocess.run(
            ["openssl", "passwd", "-apr1", password],
            capture_output=True, text=True, check=True,
        )
        return f"{user}:{out.stdout.strip()}"
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass
    raise RuntimeError(
        "neither `htpasswd` nor `openssl passwd` available — "
        "install apache2-utils or openssl."
    )


def setup_auth(cfg, config_path):
    """Generate htpasswd file if basic auth is enabled (default ON).

    Defensive: if htpasswd already exists on disk we DO NOT overwrite it.
    Use `reset-auth` to force regeneration.
    """
    serve_cfg = cfg.get("serve", {})
    auth = serve_cfg.setdefault("auth", {})
    auth.setdefault("enabled", True)
    auth.setdefault("user", "admin")
    auth.setdefault("auto_password", True)
    auth.setdefault("password", "")
    auth.setdefault("htpasswd_path", "")
    if not auth["enabled"]:
        return True, "Auth disabled in config (serve.auth.enabled = false)"
    htpasswd_path = Path(serve_cfg["root"]) / ".htpasswd"
    if htpasswd_path.exists():
        auth["htpasswd_path"] = str(htpasswd_path)
        with open(config_path, "w", encoding="utf-8") as f:
            yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
        return True, f"htpasswd already exists at {htpasswd_path} — left untouched"
    user = auth["user"]
    password = auth.get("password")
    if auth.get("auto_password") or not password:
        import secrets
        password = secrets.token_urlsafe(16)[:16]
        auth["password"] = password
    line = _make_htpasswd_line(user, password)
    htpasswd_path.parent.mkdir(parents=True, exist_ok=True)
    htpasswd_path.write_text(line + "\n", encoding="utf-8")
    htpasswd_path.chmod(0o640)
    auth["htpasswd_path"] = str(htpasswd_path)
    with open(config_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
    return True, f"htpasswd generated: {htpasswd_path}\n         user={user} password={password}  (save this — printed once)"


def print_nginx_config(cfg):
    """Print a complete nginx server block (server + location + auth + security).

    If `serve.domain` is empty, falls back to a location-only snippet so legacy
    single-server setups keep working.
    """
    serve_cfg = cfg.get("serve", {})
    url_base = serve_cfg.get("url_base", "/docs/")
    serve_root = serve_cfg["root"]
    domain = serve_cfg.get("domain", "")
    auth = serve_cfg.get("auth", {}) or {}
    project_name = cfg.get("project", {}).get("name", "Doc Index")
    short = cfg.get("project", {}).get("short_name", "docs").lower()

    if not domain:
        print("# ⚠ serve.domain not set in config.yaml — emitting location-only snippet.")
        auth_inner = ""
        if auth.get("enabled", True) and auth.get("htpasswd_path"):
            auth_inner = (
                f'    auth_basic           "{project_name}";\n'
                f'    auth_basic_user_file {auth["htpasswd_path"]};\n'
            )
        print(f"""
# Add this to an existing nginx server block:
location {url_base} {{
    alias {serve_root}/;
    index index.html;
    try_files $uri $uri/ =404;
{auth_inner}
    # --- Security: block sensitive paths ---
    location ~ /\\.git {{ deny all; return 404; }}
    location ~ /\\.env {{ deny all; return 404; }}
    location ~ /\\.(?:key|pem|p12|pfx|jks|secret|credentials) {{ deny all; return 404; }}
    location ~ /(?:__pycache__|node_modules)/ {{ deny all; return 404; }}

    # --- Security headers ---
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Cache static assets
    location ~* \\.(png|jpg|jpeg|gif|ico|css|js|pdf)$ {{
        expires 1h;
        add_header Cache-Control "public, immutable";
    }}
}}
""")
        return

    auth_block = ""
    if auth.get("enabled", True):
        htpasswd_path = auth.get("htpasswd_path") or f"{serve_root}/.htpasswd"
        auth_block = (
            f'    auth_basic           "{project_name}";\n'
            f'    auth_basic_user_file {htpasswd_path};\n'
        )
    print(f"""
# /etc/nginx/conf.d/{short}.conf — generated by doc-index serve.py
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain};

    # ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;

{auth_block}
    location {url_base} {{
        alias {serve_root}/;
        index index.html;
        try_files $uri $uri/ =404;

        # --- Security: block sensitive paths ---
        location ~ /\\.git {{ deny all; return 404; }}
        location ~ /\\.env {{ deny all; return 404; }}
        location ~ /\\.(?:key|pem|p12|pfx|jks|secret|credentials) {{ deny all; return 404; }}
        location ~ /(?:__pycache__|node_modules)/ {{ deny all; return 404; }}

        # --- Security headers ---
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;

        # Cache static assets
        location ~* \\.(png|jpg|jpeg|gif|ico|css|js|pdf)$ {{
            expires 1h;
            add_header Cache-Control "public, immutable";
        }}
    }}
}}

# Optional: redirect http -> https
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

# Save above to /etc/nginx/conf.d/<your>.conf, run `nginx -t && systemctl reload nginx`.
# Don't forget SSL: certbot --nginx -d {domain}""")


def cmd_init(config_path):
    """Full initialization."""
    cfg = load_config(config_path)
    print(f"=== Doc Index Init: {cfg['project']['name']} ===\n")

    steps = [
        ("Check nginx", lambda: check_nginx()),
        ("Check repo", lambda: check_repo(cfg["repo"]["path"])),
        ("Create serve dir", lambda: create_serve_dir(cfg["serve"]["root"])),
        ("Create docs symlink", lambda: create_docs_symlink(cfg["serve"]["root"], cfg["repo"]["path"])),
        ("Generate icons", lambda: generate_icons(cfg["serve"]["root"], cfg)),
        ("Copy templates", lambda: copy_templates(cfg["serve"]["root"])),
        ("Setup basic auth", lambda: setup_auth(cfg, config_path)),
        ("Setup cron", lambda: setup_cron(cfg, config_path)),
        ("Initial scan", lambda: run_initial_scan(cfg, config_path)),
    ]

    all_ok = True
    for step_name, step_fn in steps:
        ok, msg = step_fn()
        status = "OK" if ok else "FAIL"
        print(f"[{status}] {step_name}: {msg}")
        if not ok:
            all_ok = False

    print()
    print_nginx_config(cfg)

    if all_ok:
        print("=== Init complete! ===")
        print(f"Site: {cfg['serve'].get('url_base', '/')}")
        print("Add the nginx config above, then reload: sudo nginx -s reload")
    else:
        print("=== Init completed with errors — check FAIL items above ===")


def cmd_status(config_path):
    """Check deployment status."""
    cfg = load_config(config_path)
    print(f"=== Doc Index Status: {cfg['project']['name']} ===\n")

    checks = [
        ("nginx", check_nginx()),
        ("repo", check_repo(cfg["repo"]["path"])),
        ("serve dir", (Path(cfg["serve"]["root"]).is_dir(), cfg["serve"]["root"])),
        ("docs symlink", (
            (Path(cfg["serve"]["root"]) / "docs").is_symlink(),
            str(Path(cfg["serve"]["root"]) / "docs")
        )),
        ("index.html", (
            (Path(cfg["serve"]["root"]) / "index.html").exists(),
            str(Path(cfg["serve"]["root"]) / "index.html")
        )),
        ("icons", (
            (Path(cfg["serve"]["root"]) / "icon-192.png").exists(),
            "icon-192.png"
        )),
    ]

    for name, (ok, msg) in checks:
        status = "OK" if ok else "MISSING"
        print(f"  [{status}] {name}: {msg}")


def cmd_reset_auth(config_path):
    """Regenerate basic-auth password + htpasswd file."""
    cfg = load_config(config_path)
    serve_cfg = cfg.setdefault("serve", {})
    auth = serve_cfg.setdefault("auth", {})
    auth["password"] = ""
    auth["auto_password"] = True
    auth.setdefault("enabled", True)
    auth.setdefault("user", "admin")
    existing = auth.get("htpasswd_path") or str(Path(serve_cfg["root"]) / ".htpasswd")
    try:
        Path(existing).unlink()
    except FileNotFoundError:
        pass
    auth["htpasswd_path"] = ""
    ok, msg = setup_auth(cfg, config_path)
    print(f"[{'OK' if ok else 'FAIL'}] {msg}")
    if not ok:
        sys.exit(1)


def main():
    if len(sys.argv) < 3:
        print("Usage:")
        print("  python3 serve.py init <config.yaml>")
        print("  python3 serve.py status <config.yaml>")
        print("  python3 serve.py nginx <config.yaml>")
        print("  python3 serve.py reset-auth <config.yaml>")
        sys.exit(1)

    command = sys.argv[1]
    config_path = sys.argv[2]

    if not Path(config_path).exists():
        print(f"ERROR: Config not found: {config_path}")
        sys.exit(1)

    if command == "init":
        cmd_init(config_path)
    elif command == "status":
        cmd_status(config_path)
    elif command == "nginx":
        cfg = load_config(config_path)
        print_nginx_config(cfg)
    elif command == "reset-auth":
        cmd_reset_auth(config_path)
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)


if __name__ == "__main__":
    main()
